[package]
license = ["Apache-2.0"]
keywords = ["IT Operations/Cloud Services", "Cost/Freemium", "Vendor/Google"]
org = "ballerinax"
name = "googleapis.cloudfunctions"
icon = "icon.png"
distribution = "slbeta6"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.1.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
