[package]
license = ["Apache-2.0"]
keywords = ["IT Operations/Enterprise Architecture Tools", "Cost/Paid"]
org = "ballerinax"
name = "leanix.integrationapi"
icon = "icon.png"
distribution = "slbeta6"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.1.2"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
